### ISSUE TITLE
Ubuntu 16 Install fails

### ISSUE THREAD

**Issue by andreas-fey** [jldeen/SVCC-AzureMgmtxplat#3]
Using the provided script on a Ubuntu 16.04 machine leads to the following error after the powershell deb installation:

> powershell (6.0.0-beta.5-1ubuntu1.16.04.1) wird eingerichtet ...
> The argument 'Install-Module' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
> PowerShell v6.0.0-beta.5
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> The argument 'Import-Module' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
> PowerShell v6.0.0-beta.5
> Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by jldeen** [comment]
This has been fixed in my latest commit. In short, I should have added a -Command switch after my sudo powershell declaration. The new commands read:

#Azure RM NetCore Preview Module Install
sudo powershell -Command {Install-Module -Name AzureRM.Netcore}
sudo powershell -Command {Import-Module -Name AzureRM.Netcore}
